# Site settings
title: Data Science Journey | Jithin J Kumar, passionate student of AI,ML, Data Science, LIFE..! :D 
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "Jithin J Kumar"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
